[project]
name = "zaturn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckdb>=1.2.1",
    "fastmcp>=0.4.1",
    "pandas>=2.2.3",
    "python-lsp-server>=1.12.2",
    "sqlalchemy>=2.0.40",
]
